project:
  type: website
  output-dir: _site
  resources:
    - CNAME

website:
  title: "Patchmosaic"
  site-url: "https://patchmosaic.org"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Posts
        menu:
          - href: posts/2026-05-16-python-post/index.ipynb
            text: Python Notebook Post
          - href: posts/2026-05-17-r-post/index.Rmd
            text: R Markdown Post

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
